name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    # Add Node.js setup and npm commands here
    - name: Setup Node.js
      uses: actions/setup-node@v4 # Use the latest stable version of setup-node
      with:
        node-version: '20' # Or '18', or 'lts/*' for the latest LTS version

    - name: Install Node Dependencies
      run: npm install

    - name: Build Assets
      run: npm run build
      env:
        # This sets NODE_ENV for the build process, often used by frontend frameworks
        # like Vite or Laravel Mix to determine the build mode (e.g., production optimizations).
        NODE_ENV: production

    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test
